### ISSUE TITLE
possible expansion errors

### ISSUE THREAD

**Issue by migmanu** [migmanu/minishell#27]
Check the following cases
![Screenshot from 2023-11-27 18-47-47](https://github.com/migmanu/minishell/assets/52668755/38e80f3f-3e46-43e9-a337-26ac9c41d551)

**Comment by SebasNadu** [comment]
> * `echo $"HOME` in bash opens the terminal in wait for end of user input. Ours returns unmatch quote error, not print HOME inmediatly.
> * echo `"'$HO''ME'"` return in the spreadsheet is also wrong. Should print `'''ME'`

In the first command they are 2 single quotes, its better cpy/paste each case because sometimes is not easy to difference between single and double quote in the Excel.

**Comment by migmanu** [comment]
I see! But should ours behave the same when one double quote is used as in my example? Or is that out of our scope?

**Comment by migmanu** [comment]
"$HOMEdskjhfkdshfsd" also does not work as expected

**Comment by SebasNadu** [comment]
echo "'"h'o'la"'" 178
echo"'hola'"  179
e"cho hola" 187
e'cho hola' 188
"e"'c'ho 'b'"o"nj"o"'u'r 196
