### ISSUE TITLE
export and unset with the first char number

### ISSUE THREAD

**Issue by SebasNadu** [migmanu/minishell#69]
<img width="468" alt="Screenshot 2023-12-05 at 15 32 30" src="https://github.com/migmanu/minishell/assets/98430438/3a214639-5daf-4848-ae14-0341ac84ff02">

**Comment by SebasNadu** [comment]
Also this cases with the same message:
unset HOL?A
unset HOLA HOL?A
unset HOL?A HOLA
unset HOL?A HOL.A
unset HOLA=
unset HOLA=
unset HOL.A
unset HOL+A
unset HOL=A
unset HOL{A
unset HOL}A
unset HOL-A
unset -HOLA
unset HOL*A
unset HOL#A
unset $PWD
unset HOL^A
unset HOL\~A  => bash: unset: `HOL~': not a valid identifier
![Screenshot 2023-12-05 at 15 59 29](https://github.com/migmanu/minishell/assets/98430438/5c6aea49-c030-4491-873a-7bdd350e408d)

Other  kind of cases with unset:
unset HOL!A.   => bash: !A: event not found
unset HOL;A     => Command not found, maybe ignore this cases because depends on ; symbol

**Comment by migmanu** [comment]
I believe the spreadsheet is wrong here. My bash does not display that error with `unset`

First is mish, second is bash
![Screenshot from 2023-12-05 17-08-20](https://github.com/migmanu/minishell/assets/52668755/c43f854c-2dec-4793-9f63-36aa843dc574)

**Comment by SebasNadu** [comment]
In my Mac I had these mistake with bash. Let's test it tomorrow in the school.
